language: ruby
rvm:
  - 2.0.0
before_install:
  - git clone https://github.com/fletcher/MultiMarkdown-4.git mmd4
  - cd mmd4
  - git submodule init
  - git submodule update
  - make
  - sudo make install
script:
  - bundle exec middleman build
after_success:
  - bundle exec middleman deploy
  
