version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  basic:
    docker: 
      - image: buildpack-deps:jessie
        #working_directory: /tmp
  nixos:
    docker:
      - image: nixos/nix:latest
        #working_directory: /tmp
  nm_alt:
    docker:
      - image: lnl7/nix:latest
        #working_directory: /tmp

workflows:
  deploy_prod:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build

jobs:
  build:
    executor: nixos
    steps:
      - checkout
      - restore_cache:
          keys:
            - nix-cache
      - run: 
          name: build website
          command: nix-build
      - run: 
          name: copy website to workplace
          command: |
            mkdir -p workspace/build
            #cp -R $(nix-build --no-out-link)/* workspace/build/
            echo "hello world" > workspace/build/index.html
      - save_cache:
          key: nix-cache
          paths:
            - /nix/store
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  deploy_prod:
    executor: basic
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - gh-pages/deploy:
          build-dir: /tmp/workspace/build
          ssh-fingerprints: '51:ae:f3:4c:93:1b:38:d4:d4:2d:33:c1:aa:54:3a:a5'

#- run: 
#name: disable github jekyll
#shell: touch result/site/.nojekyll

