version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:2020.01
  node:
    docker:
      - image: circleci/node:current
  nixos:
    docker:
      - image: nixos/nix:latest
        #working_directory: /tmp
  nm_alt:
    docker:
      - image: lnl7/nix:latest
        #working_directory: /tmp

workflows:
  deploy_prod:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build

jobs:
  build:
    executor: basic
    #executor: nixos
    steps:
      - checkout
      #- restore_cache:
          #keys:
            #- nix-cache
      #- run: 
          #name: build website
          #command: nix-build
      - run: 
          name: copy website to workplace
          command: |
            mkdir -p workspace/build
            #cp -R $(nix-build --no-out-link)/* workspace/build/
            echo "hello world" > workspace/build/index.html
      #- save_cache:
          #key: nix-cache
          #paths:
            #- /nix/store
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  deploy_prod:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages@2.0.1
            git config user.email "ci-build@tomtorsneyweir.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist /tmp/workspace/build

#- run: 
#name: disable github jekyll
#shell: touch result/site/.nojekyll

