version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:2020.01
  node:
    docker:
      - image: circleci/node:current
  nixos:
    docker:
      - image: gabysbrain/website:latest
        environment:
          CACHIX_NAME: gabysbrain

# TODO: add test job
workflows:
  deploy_prod:
    jobs:
      - build
      #- build:
          #filters:
            #branches:
              #only: 
                #- master
      - deploy_prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build

jobs:
  build:
    executor: nixos
    steps:
      - run:
          name: install depdendencies
          command: |
            nix-env -iA \
              nixpkgs.texlive.combined.scheme-full
      - checkout
      - run:
          name: setup cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash
            cachix use $CACHIX_NAME
            nix path-info --all > /tmp/store-path-pre-build
      - run: 
          name: build website
          command: nix-build
      - run:
          name: create pages
          command: result/bin/site build
      - run:
          name: push to cachix
          command: |
            bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push $CACHIX_NAME"
      #- run:
          #name: test links
          #command: result/bin/site check
      - run: 
          name: copy website to workplace
          command: |
            mkdir -p workspace/build
            cp -R _site/* workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  deploy_prod:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Install and configure dependencies
          command: |
            npm install
            git config user.email "ci-build@tomtorsneyweir.com"
            git config user.name "ci-build"
      - run:
          name: Disable jekyll builds
          command: touch workspace/build/.nojekyll
      - run:
          name: setup CNAME file
          command: echo www.tomtorsneyweir.com > workspace/build/CNAME
      - add_ssh_keys:
          fingerprints:
            - "04:20:b3:77:32:f8:06:6f:02:39:01:d3:85:54:e0:15"
      - run:
          name: Deploy to gh-pages branch
          command: npm run deploy

