version: 2.1

#orbs:
  #gh-pages: sugarshin/gh-pages@0.0.6

#executors:
  #nix_machine:
    #docker:
      #- image: nixos/nix:latest
  #nm_alt:
    #docker:
      #- image: lnl7/nix:latest

#workflows:
  #deploy_prod:
    #jobs:
      #- build
      #- gh-pages/deploy:
          #build-dir: build
          #requires:
            #- build
          #ssh-fingerprints: 'ff:22:gs:v6:gg:2g:22:7j:73:gf:ja:36:ff:y2:22:89'

jobs:
  build:
    docker:
      - image: nixos/nix:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - nix-cache
      - run: 
          name: build website
          shell: $(nix-build --no-out-link)
      - save_cache:
          key: nix-cache
          paths:
            - /nix/store
#- run: 
#name: disable github jekyll
#shell: touch result/site/.nojekyll

